### PR TITLE
1.2.1 test to anchor the nft image to the screen and the current price so they are always showing even when scrolled

### PR DESCRIPTION
**Pull request by maxrioux100**

### CODE REVIEW

**Review by zaitsev11-dev — DISMISSED** [review]
See comment here:
https://github.com/maxrioux100/gamestop-nft-helper/issues/96#issuecomment-1200092333

**Comment by maxrioux100** [comment]
mdb fuck with the market css 
https://nft.gamestop.com/

**Comment by maxrioux100** [comment]
More test should be run while resizing the windows

**Comment by maxrioux100** [comment]
seems to be working now. but sometime the element doesnt spawn at the right place on the page, sometime the bar is stickied on other page when it shouldnt

**Comment by maxrioux100** [comment]
the report box is hidden sometime

**Comment by maxrioux100** [comment]
- [ ] sometime the menu bar is not full width and I don't why it happen 
- [ ] find a way to hide the thing on top of the bar
- [ ] find a way to hide the shit in the top left corner of the price module

**Comment by maxrioux100** [comment]
error_mdb

**Comment by maxrioux100** [comment]
try to store the dom and use mdb.Sticky.getinstance instead of storing the sticky

**Comment by maxrioux100** [comment]
- [ ] bug - menubar not sitcking on dynamic redirecting
- [ ] move back the things to their place if recolution go under 1281
- [ ] bug - crash when resizing

**Review by zaitsev11-dev — APPROVED** [review]

**Pull request merged**
