### PR TITLE
Refactoring into multiple files

### PR DESCRIPTION
**Pull request by zaitsev11-dev**

### CODE REVIEW

**Comment by zaitsev11-dev** [comment]
Starting work on #37

**Comment by maxrioux100** [comment]
Gonna check those later today or tomorrow

**Review by maxrioux100 — COMMENTED** [review]
Seems nice, not approving this one only because I would prefer the last PR to be merged before.

**Comment by maxrioux100** [comment]
1.1.2 was already okay, I updated it 11hours ago :P

**Pull request merged**
