### PR TITLE
DOM check before chart creation

### PR DESCRIPTION
**Pull request by zaitsev11-dev**
- Only execute plugin on token page (manifest.json update)
- Check for chart on URL load before attempting to create chart

### CODE REVIEW

**Comment by zaitsev11-dev** [comment]
solves issue #28

**Comment by maxrioux100** [comment]
To see why the matches need to not includes /token/

Open the website on any page that doesn't include /token/ and then navigate to a /token/ page without reloading and the extension won't pop up

**Comment by maxrioux100** [comment]
Plus the errors are still popping for me

**Comment by zaitsev11-dev** [comment]
I have confirmed the behavior you have identified. Thank you for the explanation. I will revert the change to manifest.json

Also, I have been able to reproduce the error, but it does not appear to be limited to viewing a page with no history after going on a page with an history. I was able to reproduce the issue by resizing the web page.

**Comment by maxrioux100** [comment]
> I have confirmed the behavior you have identified. Thank you for the explanation. I will revert the change to manifest.json
> 
> Also, I have been able to reproduce the error, but it does not appear to be limited to viewing a page with no history after going on a page with an history. I was able to reproduce the issue by resizing the web page.

nice observation, may help us solve it !

**Pull request closed without merging**
